[package]
name = "online-statistics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
ordered-float = "3.0.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3